[entryPoints]
  [entryPoints.metrics]
    address = ":8082"
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"  

# [metrics]
#   [metrics.prometheus]
#     buckets = [0.1,0.3,1.2,5.0]
#     addServicesLabels = true
#     addEntryPointsLabels = true