[entryPoints]
  [entryPoints.metrics]
    address = ":8082"
  [entryPoints.web]
    address = ":80"
  [entryPoints.traefik]
    address = ":8080"
#   [entryPoints.https]
#     address = ":443"  

# [metrics]
#   [metrics.prometheus]
#     buckets = [0.1,0.3,1.2,5.0]
#     addServicesLabels = true
#     addEntryPointsLabels = true